language: csharp
dotnet: 2.1.0
env:
  - CONFIGURATION=Release
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test Sendgrid.Webhooks.Tests/Sendgrid.Webhooks.Tests.csproj
  - dotnet pack