language: csharp
dotnet: 2.0.0
env:
  - CONFIGURATION=Release
  - DOTNET_REFERENCE_ASSEMBLIES_PATH=/usr/lib/mono/xbuild-frameworks
install:
  - dotnet restore
script:
  - dotnet test Sendgrid.Webhooks.Tests/Sendgrid.Webhooks.Tests.csproj
  - dotnet pack